name: FastAPI CI

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: cicd_training
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy to VPS
        run: |
          sudo apt-get install -y sshpass
          sshpass -p ${{secrets.HOST_PASSWORD}} ssh ${{secrets.HOST_USERNAME}}@${{secrets.HOST_IP}} "cd /home/${{secrets.HOST_USERNAME}}/cicd/training && git pull; tmux kill-session -t mysession; tmux new-session -d -s mysession 'source /home/${{secrets.HOST_USERNAME}}/cicd/training/.venv/bin/activate && pip install -r requirements.txt  && uvicorn main:app --host 0.0.0.0 --port 8089'"
