name: FastAPI CI

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    # environment: cicd_training
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /root/cicd/CICD_Trainig
            git pull
            tmux new-session -d -s mysession 'source /root/cicd/CICD_Trainig/.venv/bin/activate && pip install -r requirements.txt  && uvicorn main:app --host 0.0.0.0 --port 8089 --reload'
